{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf200
{\fonttbl\f0\fnil\fcharset0 Consolas;}
{\colortbl;\red255\green255\blue255;\red31\green118\blue44;\red27\green31\blue34;\red7\green68\blue184;
\red6\green33\blue79;\red21\green23\blue26;}
{\*\expandedcolortbl;;\cssrgb\c13333\c52549\c22745;\cssrgb\c14118\c16078\c18039;\cssrgb\c0\c36078\c77255;
\cssrgb\c1176\c18431\c38431;\cssrgb\c10588\c12157\c13725\c29804;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl400\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
version\cf3 : \cf4 0.1\cf3 \
\cf2 env\cf3 :\
\cf2 variables\cf3 :\
   \cf2 build_version\cf3 : \cf5 "0.1"\cf3 \
\cf2 phases\cf3 :\
  \cf2 install\cf3 :\
    \cf2 commands\cf3 :\
      - \cf5 yum install rpm-build make gcc glibc -y\cf3 \
  \cf2 pre_build\cf3 :\
    \cf2 commands\cf3 :\
      - \cf5 curr_working_dir=`pwd`\cf6 \
\cf3       - \cf5 mkdir -p ./\{RPMS,SRPMS,BUILD,SOURCES,SPECS,tmp\}\cf3 \
      - \cf5 filename="sample-$build_version"\cf3 \
      - \cf5 echo $filename\cf3 \
      - \cf5 mkdir -p $filename\cf3 \
      - \cf5 cp ./*.c ./*.h Makefile $filename\cf3 \
      - \cf5 tar -zcvf /root/$filename.tar.gz $filename\cf3 \
      - \cf5 cp /root/$filename.tar.gz ./SOURCES/\cf3 \
      - \cf5 cp sample.rpmspec ./SPECS/\cf3 \
  \cf2 build\cf3 :\
    \cf2 commands\cf3 :\
    - \cf5 echo "Triggering RPM build"\cf3 \
    - \cf5 rpmbuild --define "_topdir `pwd`" -ba SPECS/sample.rpmspec\cf3 \
    - \cf5 cd $curr_working_dir\cf3 \
  \cf2 artifacts\cf3 :\
  \cf2 files\cf3 :\
  - \cf5 RPMS/x86_64/sample*.rpm\cf3 \
  \cf2 discard-paths\cf3 : \cf5 yes\cf3 \
\
}